### PR TITLE
add CONTRIBUTING.md and CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by bradmccoydev**
Signed-off-by: bradmccoydev <bradmccoydev@gmail.com>

### CODE REVIEW

**Review by patchandpray — APPROVED** [review]

**Comment by patchandpray** [comment]
Thanks for adding these @bradmccoydev I approved them

**Comment by bradmccoydev** [comment]
No problem, they are pretty standard, but we can change some of the conventions etc if we want @patchandpray

**Review by verma-kunal — APPROVED** [review]
LGTM👍

Thanks for adding these @bradmccoydev

**Review by AbhijithGanesh — APPROVED** [review]
LGTM

**Pull request merged**
