### PR TITLE
Update feature.yml

### PR DESCRIPTION
**Pull request by helper-uttam**
``` diff
- Please give us the image/video (if applicable)
+ Please attach an image/video (if applicable)
```

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Hey, @helper-uttam can you please tell me more about this?

**Comment by kaiwalyakoparkar** [comment]
Kindly refer [this](https://github.com/kaiwalyakoparkar/classroom-monitor-bot/tree/main/.github/ISSUE_TEMPLATE) for all sorts of templates. We shall need more information about the pr/issue

**Comment by helper-uttam** [comment]
> Kindly refer [this](https://github.com/kaiwalyakoparkar/classroom-monitor-bot/tree/main/.github/ISSUE_TEMPLATE) for all sorts of templates. We shall need more information about the pr/issue

I had made changes referring to the repo you linked. Please review it and let me know if anything needs to be change!

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM

**Pull request merged**
